### ISSUE TITLE
Request causes application to crash

### ISSUE THREAD

**Issue by arunasank** [hotosm/OpenMapKitServer#108]
Log trace before the application crashed:

```
Feb 26 13:04:11 ip-172-31-42-111 cloud-init[1778]: ::ffff:172.31.3.181 - - [26/Feb/2019:13:04:08 +0000] "GET / HTTP/1.1" 302 32 "-" "python-requests/2.20.1"
Feb 26 13:04:11 ip-172-31-42-111 cloud-init[1778]: message repeated 30 times: [ ::ffff:172.31.3.181 - - [26/Feb/2019:13:04:08 +0000] "GET / HTTP/1.1" 302 32 "-" "python-requests/2
.20.1"]
Feb 26 13:04:11 ip-172-31-42-111 cloud-init[1778]: ::ffff:172.31.3.181 - - [26/Feb/2019:13:04:08 +0000] "GET /formList?json=true&formid=buildings HTTP/1.1" - - "-" "python-request
s/2.20.1"
Feb 26 13:04:12 ip-172-31-42-111 cloud-init[1778]: message repeated 47 times: [ ::ffff:172.31.3.181 - - [26/Feb/2019:13:04:08 +0000] "GET /formList?json=true&formid=buildings HTTP
/1.1" - - "-" "python-requests/2.20.1"]
Feb 26 13:04:12 ip-172-31-42-111 cloud-init[1778]: ::ffff:172.31.3.181 - - [26/Feb/2019:13:04:09 +0000] "GET /formList?json=true&formid=buildings HTTP/1.1" - - "-" "python-request
s/2.20.1"
Feb 26 13:04:13 ip-172-31-42-111 cloud-init[1778]: message repeated 11 times: [ ::ffff:172.31.3.181 - - [26/Feb/2019:13:04:09 +0000] "GET /formList?json=true&formid=buildings HTTP
/1.1" - - "-" "python-requests/2.20.1"]
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]: /app/node_modules/openrosa-formlist/node_modules/xmlbuilder/lib/XMLNode.js:92
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:         if (!this.options.ignoreDecorators && this.stringify.convertTextKey && name.indexOf(this.stringify.convertTextKey) === 0) {
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:                                                                                    ^
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]: TypeError: Cannot read property 'indexOf' of undefined
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:     at XMLElement.module.exports.XMLNode.element (/app/node_modules/openrosa-formlist/node_modules/xmlbuilder/lib/XMLNode.js:92:84)
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:     at XMLElement.module.exports.XMLNode.element (/app/node_modules/openrosa-formlist/node_modules/xmlbuilder/lib/XMLNode.js:62:28)
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:     at XMLElement.module.exports.XMLNode.element (/app/node_modules/openrosa-formlist/node_modules/xmlbuilder/lib/XMLNode.js:82:32)
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:     at XMLElement.module.exports.XMLNode.element (/app/node_modules/openrosa-formlist/node_modules/xmlbuilder/lib/XMLNode.js:85:25)
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:     at new XMLBuilder (/app/node_modules/openrosa-formlist/node_modules/xmlbuilder/lib/XMLBuilder.js:25:19)
Feb 26 13:04:14 ip-172-31-42-111 cloud-init[1778]:     at Object.module.exports.create (/app/node_modules/openrosa-formlist/node_modules/xmlbuilder/lib/index.js:11:12)
Feb 26 13:04:15 ip-172-31-42-111 cloud-init[1778]:     at buildXml (/app/node_modules/openrosa-formlist/index.js:79:23)
Feb 26 13:04:15 ip-172-31-42-111 cloud-init[1778]:     at /app/node_modules/openrosa-formlist/node_modules/async/lib/async.js:251:17
Feb 26 13:04:15 ip-172-31-42-111 cloud-init[1778]:     at done (/app/node_modules/openrosa-formlist/node_modules/async/lib/async.js:132:19)
Feb 26 13:04:15 ip-172-31-42-111 cloud-init[1778]:     at /app/node_modules/openrosa-formlist/node_modules/async/lib/async.js:32:16
```

**Comment by arunasank** [comment]
cc/ @hotosm/tech

**Comment by arunasank** [comment]
Another request: This was for a form that does not exist, but the application should handle it gracefully instead of crashing.

```
Feb 27 17:25:29 : { Error: ENOENT: no such file or directory, open '/app/data/forms/buildings.xlsx'
Feb 27 17:25:29 :     at Error (native)
Feb 27 17:25:29 :   errno: -2,
Feb 27 17:25:29 :   code: 'ENOENT',
Feb 27 17:25:29 :   syscall: 'open',
Feb 27 17:25:29 :   path: '/app/data/forms/buildings.xlsx' }
Feb 27 17:25:29 : _http_server.js:193
Feb 27 17:25:29 :     throw new RangeError(`Invalid status code: ${statusCode}`);
Feb 27 17:25:29 :     ^
Feb 27 17:25:29 : RangeError: Invalid status code: 0
Feb 27 17:25:29 :     at ServerResponse.writeHead (_http_server.js:193:11)
Feb 27 17:25:29 :     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:55:19)
Feb 27 17:25:29 :     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:55:19)
Feb 27 17:25:29 :     at ServerResponse._implicitHeader (_http_server.js:158:8)
Feb 27 17:25:29 :     at ServerResponse.OutgoingMessage.write (_http_outgoing.js:460:10)
Feb 27 17:25:29 :     at writetop (/app/node_modules/express-session/index.js:290:26)
Feb 27 17:25:29 :     at ServerResponse.end (/app/node_modules/express-session/index.js:351:16)
Feb 27 17:25:29 :     at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
Feb 27 17:25:29 :     at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
Feb 27 17:25:29 :     at ReadFileContext.fs.readFile.e [as callback] (/app/api/odk/odk-data.js:20:37)
```

**Comment by arunasank** [comment]
Seeing the same crash that we saw in the earlier comment, again on the `tanzania` stack, when trying to query for a form that does not exist. Querying for a form that does not exist should not cause our servers to crash - it should be handled gracefully:
```
::ffff:172.31.80.82 - - [07/Mar/2019:08:31:58 +0000] "GET /formList?json=true&formid=buildings HTTP/1.1" 200 86 "-" "python-requests/2.9.1"
{ Error: ENOENT: no such file or directory, open '/app/data/forms/buildings.xlsx'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/data/forms/buildings.xlsx' }
_http_server.js:200
    throw new RangeError(`Invalid status code: ${originalStatusCode}`);
    ^

RangeError: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:200:11)
    at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:191:8)
    at write_ (_http_outgoing.js:632:9)
    at ServerResponse.write (_http_outgoing.js:617:10)
    at writetop (/app/node_modules/express-session/index.js:290:26)
    at ServerResponse.end (/app/node_modules/express-session/index.js:351:16)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
```

**Comment by arunasank** [comment]
Request history from the server crash today:

```
::ffff:172.31.26.77 - - [11/Mar/2019:11:01:46 +0000] "POST /submission?deviceID=imei:353147084720046 HTTP/1.1" 201 94 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0; TECNO W5 Lite Build
/MRA58K) org.odk.collect.android/v1.10.1-33-g7cfe909"
Automatic OMK submission OSM API error. {"msg":"Error creating changeset.","err":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"osm.posm.io","host":"o
sm.posm.io","port":80}}
All changesets in the queue have been submitted.
Upload to S3 completed.
got file named xml_submission_file
got file named 6c04492c739ce5f0998e257c52b1716aeaca0b11.osm
got file named 1552299425773.jpg
Upload completed!
::ffff:172.31.26.77 - - [11/Mar/2019:11:02:21 +0000] "POST /submission?deviceID=imei:353147084720046 HTTP/1.1" 201 94 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0; TECNO W5 Lite Build
/MRA58K) org.odk.collect.android/v1.10.1-33-g7cfe909"
Automatic OMK submission OSM API error. {"msg":"Error creating changeset.","err":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"osm.posm.io","host":"o
sm.posm.io","port":80}}
All changesets in the queue have been submitted.
Upload to S3 completed.
::ffff:172.31.26.77 - - [11/Mar/2019:11:02:21 +0000] "GET / HTTP/1.1" 302 32 "-" "ELB-HealthChecker/2.0"
::ffff:172.31.74.185 - - [11/Mar/2019:11:02:23 +0000] "GET / HTTP/1.1" 302 32 "-" "ELB-HealthChecker/2.0"
got file named xml_submission_file
got file named 6c5bf8fef94d5140941bd0f3db042e5b746d425c.osm
got file named 1552299524096.jpg
Upload completed!
::ffff:172.31.26.77 - - [11/Mar/2019:11:03:00 +0000] "POST /submission?deviceID=imei:353147084720046 HTTP/1.1" 201 94 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0; TECNO W5 Lite Build/MRA58K) org.odk.collect.android/v1.10.1-33-g7cfe909"
Automatic OMK submission OSM API error. {"msg":"Error creating changeset.","err":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"osm.posm.io","host":"osm.posm.io","port":80}}
All changesets in the queue have been submitted.
Upload to S3 completed.
::ffff:172.31.26.77 - - [11/Mar/2019:11:04:52 +0000] "POST /submission?deviceID=imei:353147084720046 HTTP/1.1" - - "-" "Dalvik/2.1.0 (Linux; U; Android 6.0; TECNO W5 Lite Build/MRA58K) org.odk.collect.android/v1.10.1-33-g7cfe909"
/app/api/odk/middlewares/openrosa-form-submission-middleware.js:131
            Object.keys(fields).forEach(function(name) {
                   ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /app/api/odk/middlewares/openrosa-form-submission-middleware.js:131:20
    at /app/node_modules/multiparty/index.js:123:9
    at /app/node_modules/multiparty/index.js:115:9
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by arunasank** [comment]
Saw another occurrence of the same request in the above comment today morning.

**Comment by willemarcel** [comment]
> Feb 27 17:25:29 : { Error: ENOENT: no such file or directory, open '/app/data/forms/buildings.xlsx'
> Feb 27 17:25:29 :     at Error (native)
> Feb 27 17:25:29 :   errno: -2,
> Feb 27 17:25:29 :   code: 'ENOENT',
> Feb 27 17:25:29 :   syscall: 'open',
> Feb 27 17:25:29 :   path: '/app/data/forms/buildings.xlsx' }
> Feb 27 17:25:29 : _http_server.js:193
> Feb 27 17:25:29 :     throw new RangeError(`Invalid status code: ${statusCode}`);
> Feb 27 17:25:29 :     ^

I fixed that one :top: .

> Feb 26 13:04:12 ip-172-31-42-111 cloud-init[1778]: ::ffff:172.31.3.181 - - [26/Feb/2019:13:04:09 +0000] "GET /formList?json=true&formid=buildings HTTP/1.1" - - "-" "python-request
> s/2.20.1"

I couldn't reproduce that one... it doesn't fail.

**Comment by willemarcel** [comment]
> ::ffff:172.31.26.77 - - [11/Mar/2019:11:04:52 +0000] "POST /submission?deviceID=imei:353147084720046 HTTP/1.1" - - "-" "Dalvik/2.1.0 (Linux; U; Android 6.0; TECNO W5 Lite Build/MRA58K) org.odk.collect.android/v1.10.1-33-g7cfe909"
> /app/api/odk/middlewares/openrosa-form-submission-middleware.js:131
>             Object.keys(fields).forEach(function(name) {
>                    ^
> 
> TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at /app/api/odk/middlewares/openrosa-form-submission-middleware.js:131:20
>     at /app/node_modules/multiparty/index.js:123:9
>     at /app/node_modules/multiparty/index.js:115:9
>     at _combinedTickCallback (internal/process/next_tick.js:132:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:219:9)

Fixed this with https://github.com/hotosm/OpenMapKitServer/pull/116
