### ISSUE TITLE
Archive form error

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#23]
@willemarcel When selecting archive form option, I'm seeing these errors and the app crashing. Archive form isn't completed. Is there anything we need to change on the deployment side of things? 

```
::ffff:172.17.0.1 - - [05/Apr/2018:09:10:05 +0000] "GET /formList?json=true&formid=nmp_buildings_v_testing_01 HTTP/1.1" 304 - "https://botswana-test.hotosm.org/omk/pages/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
::ffff:172.17.0.1 - admin [05/Apr/2018:09:10:17 +0000] "POST /omk/odk/forms/nmp_buildings_v_testing_01/archive HTTP/1.1" 200 40 "https://botswana-test.hotosm.org/omk/pages/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
    at fs.mkdir.mkdirError (/app/api/odk/controllers/archive-form.js:45:34)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by willemarcel** [comment]
I fixed some errors in https://github.com/hotosm/OpenMapKitServer/commit/6847b3956892d9c9f28650c21c3fc8105ae8c17a

I tested in the evennode server and it worked. @smit1678 could you confirm?

**Comment by smit1678** [comment]
@willemarcel Ok, I deployed the updates and I don't see this error happening anymore but the archive still isn't completing. Maybe this is due to nginx or some directory permissions.

It seems that `https://botswana-test.hotosm.org/omk/odk/archived-forms` is getting a bad gateway and then throws this error: 

```
/app/api/odk/controllers/archived-form-list.js:11
      {forms: items.filter(i => i.endsWith('.xml')).map(i => path.basename(i, '.xml'))}
                   ^

TypeError: Cannot read property 'filter' of undefined
    at fs.readdir (/app/api/odk/controllers/archived-form-list.js:11:20)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by willemarcel** [comment]
The error was caused due to the lack of permissions to create the archive dirs. I committed the archive dirs.
